export const SUBMIT_ORDER = 'SUBMIT_ORDER';
export const GET_ORDERLIST = 'GET_ORDERLIST';

export const LOAD_ORDERS_START = 'LOAD_ORDERS_START';
export const LOAD_ORDERS_SUCCESS = 'LOAD_ORDERS_SUCCESS';
export const LOAD_ORDERS_FAIL = 'LOAD_ORDERS_FAIL';

export const LOAD_FILES_START = 'LOAD_FILES_START';
export const LOAD_FILES_SUCCESS = 'LOAD_FILES_SUCCESS';
export const LOAD_FILES_FAIL = 'LOAD_FILES_FAIL';
